name: configcat
version: '#VERSION_PLACEHOLDER#'
base: core20
summary: Command Line Interface for ConfigCat
description: |
  The ConfigCat Command Line Interface allows you to interact with the ConfigCat Management API via the command line.
  It supports most functionality found on the ConfigCat Dashboard. You can manage ConfigCat 
  resources like Feature Flags, Targeting / Percentage rules, Products, Configs, Environments, and more.
license: MIT

grade: stable
confinement: strict

parts:
  configcat:
    plugin: dump
    source: linux-x64/
    organize:
      configcat: bin/
    stage:
      - bin/configcat
      - LICENSE
      - README.md
    override-build: |
      cd $SNAPCRAFT_PART_BUILD
      chmod +x configcat
      snapcraftctl build

apps:
  configcat:
    command: bin/configcat
    plugs:
      - home
      - network
