name: ConfigCat CLI CI

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
  
jobs:
  produce-executables:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [win-x64, linux-x64, linux-musl-x64, osx-x64]

    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '5.0.x'
        
    - name: Publish ${{ matrix.arch }}
      run: | 
        dotnet publish src/ConfigCat.Cli/ConfigCat.Cli.csproj -c Release -r ${{ matrix.arch }} --self-contained true -p:PublishSingleFile=true -o publish/${{ matrix.arch }}
        cp LICENSE publish/${{ matrix.arch }}/LICENSE
        cp README.md publish/${{ matrix.arch }}/README.md

    - name: Archive executables
      uses: actions/upload-artifact@v2
      with:
        name: executables
        path: publish
      
  linux-tests:
    needs: produce-executables
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Download executables
      uses: actions/download-artifact@v2
      with:
        name: executables

    - name: Update version in snapcraft
      run: sed -i 's/#VERSION_PLACEHOLDER#/0.0.1/g' snap/snapcraft.yaml

    - name: Build snap
      uses: snapcore/action-build@v1
      id: build

    - name: Install snap
      run: sudo snap install --dangerous ${{ steps.build.outputs.snap }}

    - name: Execute tests
      shell: pwsh
      run: ./test/integ.ps1 configcat
      env:
        CONFIGCAT_API_HOST: ${{ secrets.CONFIGCAT_API_HOST }}
        CONFIGCAT_API_USER: ${{ secrets.CONFIGCAT_API_USER }}
        CONFIGCAT_API_PASS: ${{ secrets.CONFIGCAT_API_PASS }}

  win-tests:
    needs: produce-executables
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Download executables
      uses: actions/download-artifact@v2
      with:
        name: executables

    - name: Update version in nuspec
      run: ((Get-Content -path choco\configcat.nuspec -Raw) -replace '#VERSION_PLACEHOLDER#','0.0.1') | Set-Content -Path choco\configcat.nuspec
      shell: powershell

    - name: Install local choco package
      run: choco install choco\configcat.nuspec

    - name: Execute tests
      shell: pwsh
      run: ./test/integ.ps1 configcat
      env:
        CONFIGCAT_API_HOST: ${{ secrets.CONFIGCAT_API_HOST }}
        CONFIGCAT_API_USER: ${{ secrets.CONFIGCAT_API_USER }}
        CONFIGCAT_API_PASS: ${{ secrets.CONFIGCAT_API_PASS }}

  mac-tests:
    needs: produce-executables
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Download executables
      uses: actions/download-artifact@v2
      with:
        name: executables

    - name: Execute tests
      shell: pwsh
      run: |
        chmod +x ./osx-x64/configcat
        ./test/integ.ps1 ./osx-x64/configcat
      env:
        CONFIGCAT_API_HOST: ${{ secrets.CONFIGCAT_API_HOST }}
        CONFIGCAT_API_USER: ${{ secrets.CONFIGCAT_API_USER }}
        CONFIGCAT_API_PASS: ${{ secrets.CONFIGCAT_API_PASS }}

  docker-tests:
    needs: produce-executables
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Download executables
      uses: actions/download-artifact@v2
      with:
        name: executables

    - name: Set permissions
      run: chmod +x ./linux-musl-x64/configcat

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: configcat/cli:dev

    - name: Execute tests
      shell: pwsh
      run: |
        ./test/integ.ps1 "docker run --rm \
        --env CONFIGCAT_API_HOST=${{ secrets.CONFIGCAT_API_HOST }} \
        --env CONFIGCAT_API_USER=${{ secrets.CONFIGCAT_API_USER }} \
        --env CONFIGCAT_API_PASS=${{ secrets.CONFIGCAT_API_PASS }} \
        configcat/cli:dev"