name: ConfigCat CLI CI

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
  
jobs:
  produce-executables:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '5.0.x'
        
    - name: Publish Windows
      run: |
        dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o publish/win
        cp test/integ.ps1 publish/win/integ.ps1

    - name: Publish Linux
      run: |
        dotnet publish -c Release -r linux-x64 --self-contained true -p:PublishSingleFile=true -o publish/linux
        cp test/integ.ps1 publish/linux/integ.ps1

    - name: Publish macOS
      run: |
        dotnet publish -c Release -r osx-x64 --self-contained true -p:PublishSingleFile=true -o publish/mac
        cp test/integ.ps1 publish/mac/integ.ps1

    - name: Archive executables
      uses: actions/upload-artifact@v2
      with:
        name: executables
        path: publish
      
  linux-tests:
    needs: produce-executables
    runs-on: ubuntu-latest
    
    steps:
    - name: Download executables
      uses: actions/download-artifact@v2
      with:
        name: executables

    - name: Execute tests
      shell: pwsh
      run: |
        cd linux
        ./integ.ps1
      env:
        CONFIGCAT_API_HOST: ${{ secrets.CONFIGCAT_API_HOST }}
        CONFIGCAT_API_USER: ${{ secrets.CONFIGCAT_API_USER }}
        CONFIGCAT_API_PASS: ${{ secrets.CONFIGCAT_API_PASS }}

  win-tests:
    needs: produce-executables
    runs-on: windows-latest
    
    steps:
    - name: Download executables
      uses: actions/download-artifact@v2
      with:
        name: executables

    - name: Execute tests
      shell: pwsh
      run: |
        cd win
        ./integ.ps1
      env:
        CONFIGCAT_API_HOST: ${{ secrets.CONFIGCAT_API_HOST }}
        CONFIGCAT_API_USER: ${{ secrets.CONFIGCAT_API_USER }}
        CONFIGCAT_API_PASS: ${{ secrets.CONFIGCAT_API_PASS }}

  mac-tests:
    needs: produce-executables
    runs-on: macos-latest
    
    steps:
    - name: Download executables
      uses: actions/download-artifact@v2
      with:
        name: executables

    - name: Execute tests
      shell: pwsh
      run: |
        cd mac
        ./integ.ps1
      env:
        CONFIGCAT_API_HOST: ${{ secrets.CONFIGCAT_API_HOST }}
        CONFIGCAT_API_USER: ${{ secrets.CONFIGCAT_API_USER }}
        CONFIGCAT_API_PASS: ${{ secrets.CONFIGCAT_API_PASS }}