name: ConfigCat CLI CI

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
  
jobs:
  produce-executables:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '5.0.x'
        
    - name: Publish Windows
      run: dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o publish/win

    - name: Publish Linux
      run: dotnet publish -c Release -r linux-x64 --self-contained true -p:PublishSingleFile=true -p:PublishReadyToRun=true -o publish/linux

    - name: Publish macOS
      run: dotnet publish -c Release -r osx-x64 --self-contained true -p:PublishSingleFile=true -p:PublishReadyToRun=true -o publish/mac

    - name: Archive executables
      uses: actions/upload-artifact@v2
      with:
        name: exes
        path: publish
      
  linux-tests:
    needs: produce-executables
    runs-on: ubuntu-latest
    
    steps:
    - name: Download executables
      uses: actions/download-artifact@v2
      with:
        name: exes

    - name: List folder
      run: ls

  win-tests:
    needs: produce-executables
    runs-on: windows-latest
    
    steps:
    - name: Download executables
      uses: actions/download-artifact@v2
      with:
        name: exes

    - name: List folder
      run: dir

  mac-tests:
    needs: produce-executables
    runs-on: macos-latest
    
    steps:
    - name: Download executables
      uses: actions/download-artifact@v2
      with:
        name: exes

    - name: List folder
      run: ls