name: ConfigCat CLI Docker Dev Publish

on:
  workflow_dispatch:
    
jobs:
  produce-executables:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [linux-musl-x64]
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publish ${{ matrix.arch }}
        run: |
          dotnet publish src/ConfigCat.Cli/ConfigCat.Cli.csproj -c Release -r ${{ matrix.arch }} --self-contained true -p:PublishSingleFile=true -p:Version=${{ env.VERSION }} -o publish/${{ matrix.arch }}
          cp LICENSE publish/${{ matrix.arch }}/LICENSE
          cp README.md publish/${{ matrix.arch }}/README.md
        env:
          VERSION: 0.0.1

      - name: Archive executables
        uses: actions/upload-artifact@v4
        with:
          name: executables
          path: publish
          
  docker:
    runs-on: ubuntu-latest
    needs: [ produce-executables ]

    steps:
      - uses: actions/checkout@v4

      - name: Download executables
        uses: actions/download-artifact@v4
        with:
          name: executables

      - name: Set permissions
        run: chmod +x ./linux-musl-x64/configcat

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            configcat/cli:dev-${{ github.run_id }}
            
  docker-azure:
    runs-on: ubuntu-latest
    needs: [ produce-executables ]

    steps:
      - uses: actions/checkout@v4

      - name: Download executables
        uses: actions/download-artifact@v4
        with:
          name: executables

      - name: Set permissions
        run: chmod +x ./linux-musl-x64/configcat

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: azure-devops/Dockerfile
          push: true
          tags: configcat/cli:dev-azure-devops-${{ github.run_id }}