name: ConfigCat CLI Publish

on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+']

  workflow_dispatch:

jobs:
  produce-executables:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [win-x64, win-x86, win-arm, win-arm64, linux-x64, linux-musl-x64, linux-arm, linux-arm64, osx-x64]
    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '5.0.x'
    
    - name: Get version from tag
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

    - name: Publish ${{ matrix.arch }}
      run: |
        dotnet publish src/ConfigCat.Cli/ConfigCat.Cli.csproj -c Release -r ${{ matrix.arch }} --self-contained true -p:PublishSingleFile=true -p:Version=${{ env.VERSION }} -o publish/${{ matrix.arch }}
        cp LICENSE publish/${{ matrix.arch }}/LICENSE
        cp README.md publish/${{ matrix.arch }}/README.md

    - name: Archive executables
      uses: actions/upload-artifact@v2
      with:
        name: executables
        path: publish


  snap:
    runs-on: ubuntu-latest
    needs: produce-executables

    steps:
    - uses: actions/checkout@v2

    - name: Download executables
      uses: actions/download-artifact@v2
      with:
        name: executables

    - name: Get version from tag
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

    - name: Update version in snapcraft
      run: sed -i 's/#VERSION_PLACEHOLDER#/${{ env.VERSION }}/g' snap/snapcraft.yaml

    - name: Build snap
      uses: snapcore/action-build@v1
      id: build

    - name: Archive snap
      uses: actions/upload-artifact@v2
      with:
        name: snap-pack
        path: configcat_*.snap

    # - name: 🚀Publish
    #   uses: snapcore/action-publish@v1
    #   with:
    #     store_login: ${{ secrets.SNAP_LOGIN }}
    #     snap: ${{ steps.build.outputs.snap }}
    #     release: stable

  chocolatey:
    runs-on: windows-latest
    needs: produce-executables

    steps:
    - uses: actions/checkout@v2

    - name: Download executables
      uses: actions/download-artifact@v2
      with:
        name: executables

    - name: Get version from tag
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      shell: bash

    - name: Update version in nuspec
      run: ((Get-Content -path choco\configcat.nuspec -Raw) -replace '#VERSION_PLACEHOLDER#','${{ env.VERSION }}') | Set-Content -Path choco\configcat.nuspec
      shell: powershell

    - name: Pack
      run: choco pack choco\configcat.nuspec

    - name: Archive choco package
      uses: actions/upload-artifact@v2
      with:
        name: choco-pack
        path: configcat.*.nupkg

    # - name: 🚀Publish
    #   run: |
    #     choco apikey --key ${{ secrets.CHOCO_API_KEY }} --source https://push.chocolatey.org/
    #     choco push configcat.${{ env.VERSION }}.nupkg --source https://push.chocolatey.org/

  github-release:
    runs-on: ubuntu-latest
    needs: produce-executables

    steps:
    - name: Download executables
      uses: actions/download-artifact@v2
      with:
        name: executables

    - name: Get version from tag
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

    - name: Create archives & checksum
      run: |
        chmod +x linux-x64/configcat linux-musl-x64/configcat linux-arm/configcat linux-arm64/configcat osx-x64/configcat
        cd linux-x64/ && tar --exclude='*.pdb' -czf ../configcat-cli_${{ env.VERSION }}_linux-x64.tar.gz * && cd ..
        cd linux-musl-x64/ && tar --exclude='*.pdb' -czf ../configcat-cli_${{ env.VERSION }}_linux-musl-x64.tar.gz * && cd ..
        cd linux-arm/ && tar --exclude='*.pdb' -czf ../configcat-cli_${{ env.VERSION }}_linux-arm.tar.gz * && cd ..
        cd linux-arm64/ && tar --exclude='*.pdb' -czf ../configcat-cli_${{ env.VERSION }}_linux-arm64.tar.gz * && cd ..
        cd osx-x64/ && tar --exclude='*.pdb' -czf ../configcat-cli_${{ env.VERSION }}_osx-x64.tar.gz * && cd ..
        zip -r -D configcat-cli_${{ env.VERSION }}_win-x64.zip win-x64/* -x '*.pdb'
        zip -r -D configcat-cli_${{ env.VERSION }}_win-x86.zip win-x86/* -x '*.pdb'
        zip -r -D configcat-cli_${{ env.VERSION }}_win-arm.zip win-arm/* -x '*.pdb'
        zip -r -D configcat-cli_${{ env.VERSION }}_win-arm64.zip win-arm64/* -x '*.pdb'
        
        sha256sum configcat-cli_${{ env.VERSION }}_linux-x64.tar.gz \
        configcat-cli_${{ env.VERSION }}_linux-musl-x64.tar.gz \
        configcat-cli_${{ env.VERSION }}_linux-arm.tar.gz \
        configcat-cli_${{ env.VERSION }}_linux-arm64.tar.gz \
        configcat-cli_${{ env.VERSION }}_osx-x64.tar.gz \
        configcat-cli_${{ env.VERSION }}_win-x64.zip \
        configcat-cli_${{ env.VERSION }}_win-x86.zip \
        configcat-cli_${{ env.VERSION }}_win-arm.zip \
        configcat-cli_${{ env.VERSION }}_win-arm64.zip > configcat-cli_${{ env.VERSION }}_checksums.sha256

    - name: 🚀Update release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "configcat-cli_*.tar.gz,configcat-cli_*.zip,configcat-cli_*_checksums.sha256"
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}